// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcbomutuhqqrhxmoxtbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjYm9tdXR1aHFxcmh4bW94dGJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwOTA2NjUsImV4cCI6MjA1NTY2NjY2NX0.7EcA-68_B5Q22M7WIwiV4oAG0N71kTNSAG9k6-MYRBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);